catalog:
  "@antfu/eslint-config": ^5.4.1
  "@changesets/cli": ^2.29.7
  "@commitlint/cli": ^19.8.1
  "@commitlint/config-conventional": ^19.8.1
  "@commitlint/types": ^19.8.1
  "@eslint/compat": ^1.3.2
  "@total-typescript/ts-reset": ^0.6.1
  "@tsconfig/node-lts": ^22.0.1
  "@tsconfig/node-ts": ^23.6.1
  "@tsconfig/node23": ^23.0.2
  "@tsconfig/strictest": ^2.0.5
  "@tsconfig/vite-react": ^6.3.5
  "@types/lint-staged": ^14.0.0
  "@types/node": ^24.5.2
  "@vp-tw/eslint-config": ^0.2.0
  commitizen: ^4.3.1
  cspell: ^9.2.1
  eslint: ^9.36.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-mdx: ^3.6.2
  eslint-plugin-package-json: ^0.56.3
  eslint-plugin-prettier: ^5.5.4
  husky: ^9.1.7
  jiti: ^2.5.1
  lint-staged: ^16.1.6
  pathe: ^2.0.3
  prettier: ^3.6.2
  typescript: ^5.9.2

onlyBuiltDependencies:
  - unrs-resolver
packages:
  - packages/*
