catalog:
  "@antfu/eslint-config": ^4.3.0
  "@commitlint/cli": ^19.7.1
  "@commitlint/config-conventional": ^19.7.1
  "@commitlint/types": ^19.5.0
  "@eslint/compat": ^1.2.7
  "@total-typescript/ts-reset": ^0.6.1
  "@tsconfig/node-lts": ^22.0.1
  "@tsconfig/node-ts": ^23.6.0
  "@tsconfig/node23": ^23.0.0
  "@tsconfig/strictest": ^2.0.5
  "@tsconfig/vite-react": ^3.4.0
  "@types/lint-staged": ^13.3.0
  "@types/node": ^22.13.7
  "@vp-tw/eslint-config": ^0.0.25
  commitizen: ^4.3.1
  cspell: ^8.17.5
  eslint: ^9.21.0
  eslint-config-prettier: ^10.0.2
  eslint-plugin-mdx: ^3.1.5
  eslint-plugin-package-json: ^0.26.0
  eslint-plugin-prettier: ^5.2.3
  husky: ^9.1.7
  jiti: ^2.4.2
  lint-staged: ^15.4.3
  pathe: ^2.0.3
  prettier: ^3.5.2
  typescript: ^5.8.2
packages:
  - packages/*
