catalog:
  "@antfu/eslint-config": ^4.13.2
  "@changesets/cli": ^2.29.4
  "@commitlint/cli": ^19.8.1
  "@commitlint/config-conventional": ^19.8.1
  "@commitlint/types": ^19.8.1
  "@eslint/compat": ^1.2.9
  "@total-typescript/ts-reset": ^0.6.1
  "@tsconfig/node-lts": ^22.0.1
  "@tsconfig/node-ts": ^23.6.1
  "@tsconfig/node23": ^23.0.2
  "@tsconfig/strictest": ^2.0.5
  "@tsconfig/vite-react": ^6.3.5
  "@types/lint-staged": ^13.3.0
  "@types/node": ^22.15.29
  "@vp-tw/eslint-config": ^0.1.2
  commitizen: ^4.3.1
  cspell: ^9.0.2
  eslint: ^9.28.0
  eslint-config-prettier: ^10.1.5
  eslint-plugin-mdx: ^3.4.2
  eslint-plugin-package-json: ^0.33.0
  eslint-plugin-prettier: ^5.4.1
  husky: ^9.1.7
  jiti: ^2.4.2
  lint-staged: ^16.1.0
  pathe: ^2.0.3
  prettier: ^3.5.3
  typescript: ^5.8.3
onlyBuiltDependencies:
  - unrs-resolver
packages:
  - packages/*
